
name: Terraform Azure Infrastructure

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: ./root
  TF_IN_AUTOMATION: true

jobs:

  # ==========================================================
  # TERRAFORM PLAN 
  # ==========================================================

  terraform-plan:

    name: Terraform Plan

    runs-on: ubuntu-latest

    steps:

      # --------------------------------
      # Checkout Code
      # --------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4


      # --------------------------------
      # Setup Terraform
      # --------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8


      # --------------------------------
      # Azure Login
      # --------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # --------------------------------
      # Terraform Format
      # --------------------------------

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -check -recursive


      # --------------------------------
      # Terraform Init
      # --------------------------------

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false


      # --------------------------------
      # Terraform Validate
      # --------------------------------

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform validate


      # --------------------------------
      # Terraform Plan
      # --------------------------------

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan \
            -input=false \
            -out=tfplan


      # --------------------------------
      # Upload Plan
      # --------------------------------

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./root/tfplan


  # ==========================================================
  # TERRAFORM APPLY
  # ==========================================================

  terraform-apply:

    name: Terraform Apply

    runs-on: ubuntu-latest

    needs:
      - terraform-plan

    # Apply ONLY on main branch

    if: github.ref == 'refs/heads/main'

    # GitHub Environment Approval

    environment:
      name: production

    steps:

      # --------------------------------
      # Checkout Code
      # --------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4


      # --------------------------------
      # Setup Terraform
      # --------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8


      # --------------------------------
      # Azure Login
      # --------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.d2f0e88f-01c1-4394-ab35-58a50e2b88f1 }}
          tenant-id: ${{ secrets.e5273632-114a-4cbd-9c0d-bdc7d468329b }}
          subscription-id: ${{ secrets.ba256abb-cf64-41d5-99f2-6c1d2b097fa9 }}


      # --------------------------------
      # Terraform Init
      # --------------------------------

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false


      # --------------------------------
      # Download Plan
      # --------------------------------

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./root


      # --------------------------------
      # Terraform Apply
      # --------------------------------

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            tfplan
