# name: Terraform Azure Infrastructure

# on:
#   push:
#     branches:
#       - main
#       - 'feature/**'

#   pull_request:
#     branches:
#       - main

#   workflow_dispatch:

# permissions:
#   contents: read
#   id-token: write
#   pull-requests: write

# env:
#   TF_WORKING_DIR: ./root
#   TF_IN_AUTOMATION: true

# jobs:

#   # ==========================================================
#   # 1. SECURITY SCAN
#   # ==========================================================

#   security-scan:

#     name: Terraform Security Scan

#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       # -------------------------------
#       # Gitleaks
#       # -------------------------------

#       - name: Gitleaks Scan
#         uses: gitleaks/gitleaks-action@v2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       # -------------------------------
#       # TFLint
#       # -------------------------------

#       - name: Setup TFLint
#         uses: terraform-linters/setup-tflint@v4

#       - name: Run TFLint
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           tflint --init
#           tflint

#       # -------------------------------
#       # tfsec
#       # -------------------------------

#       - name: Run tfsec
#         uses: aquasecurity/tfsec-action@v1.0.3
#         with:
#           working_directory: ${{ env.TF_WORKING_DIR }}

#       # -------------------------------
#       # Checkov
#       # -------------------------------

#       - name: Run Checkov
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           directory: ./root
#           framework: terraform
#           soft_fail: false


#   # ==========================================================
#   # 2. TERRAFORM VALIDATION
#   # ==========================================================

#   terraform-validate:

#     name: Terraform Validate

#     runs-on: ubuntu-latest

#     needs:
#       - security-scan

#     steps:

#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9.8

#       - name: Terraform Format Check
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform fmt -check -recursive

#       - name: Terraform Init
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform init -input=false

#       - name: Terraform Validate
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform validate


#   # ==========================================================
#   # 3. TERRAFORM PLAN
#   # ==========================================================

#   terraform-plan:

#     name: Terraform Plan

#     runs-on: ubuntu-latest

#     needs:
#       - terraform-validate

#     steps:

#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9.8

#       # --------------------------------
#       # Azure Authentication
#       # --------------------------------

#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       # --------------------------------
#       # Terraform Init
#       # --------------------------------

#       - name: Terraform Init
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform init -input=false

#       # --------------------------------
#       # Terraform Plan
#       # --------------------------------

#       - name: Terraform Plan
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform plan \
#             -input=false \
#             -out=tfplan

#       # --------------------------------
#       # Upload Plan
#       # --------------------------------

#       - name: Upload Terraform Plan
#         uses: actions/upload-artifact@v4
#         with:
#           name: terraform-plan
#           path: ./root/tfplan


#   # ==========================================================
#   # 4. TERRAFORM APPLY
#   # ==========================================================

#   terraform-apply:

#     name: Terraform Apply

#     runs-on: ubuntu-latest

#     needs:
#       - terraform-plan

#     # GitHub Environment
#     # Configure required approval
#     # in:
#     # Repository → Settings → Environments → production

#     if: github.ref == 'refs/heads/main'

#     environment:
#       name: production

#     steps:

#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9.8

#       # --------------------------------
#       # Azure Login
#       # --------------------------------

#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       # --------------------------------
#       # Terraform Init
#       # --------------------------------

#       - name: Terraform Init
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform init -input=false

#       # --------------------------------
#       # Download Plan
#       # --------------------------------

#       - name: Download Terraform Plan
#         uses: actions/download-artifact@v4
#         with:
#           name: terraform-plan
#           path: ./root

#       # --------------------------------
#       # Terraform Apply
#       # --------------------------------

#       - name: Terraform Apply
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: |
#           terraform apply \
#             -input=false \
#             -auto-approve \
#             tfplan


            #-----------------------------------------------------------------------------------------------------------
                
                

name: Terraform Azure Infrastructure

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: ./root
  TF_IN_AUTOMATION: true

jobs:

  # ==========================================================
  # TERRAFORM PLAN
  # ==========================================================

  terraform-plan:

    name: Terraform Plan

    runs-on: ubuntu-latest

    steps:

      # --------------------------------
      # Checkout Code
      # --------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4


      # --------------------------------
      # Setup Terraform
      # --------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8


      # --------------------------------
      # Azure Login
      # --------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # --------------------------------
      # Terraform Format
      # --------------------------------

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -check -recursive


      # --------------------------------
      # Terraform Init
      # --------------------------------

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false


      # --------------------------------
      # Terraform Validate
      # --------------------------------

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform validate


      # --------------------------------
      # Terraform Plan
      # --------------------------------

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan \
            -input=false \
            -out=tfplan


      # --------------------------------
      # Upload Plan
      # --------------------------------

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./root/tfplan


  # ==========================================================
  # TERRAFORM APPLY
  # ==========================================================

  terraform-apply:

    name: Terraform Apply

    runs-on: ubuntu-latest

    needs:
      - terraform-plan

    # Apply ONLY on main branch

    if: github.ref == 'refs/heads/main'

    # GitHub Environment Approval

    environment:
      name: production

    steps:

      # --------------------------------
      # Checkout Code
      # --------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4


      # --------------------------------
      # Setup Terraform
      # --------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8


      # --------------------------------
      # Azure Login
      # --------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # --------------------------------
      # Terraform Init
      # --------------------------------

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false


      # --------------------------------
      # Download Plan
      # --------------------------------

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./root


      # --------------------------------
      # Terraform Apply
      # --------------------------------

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            tfplan